#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=1:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=50G                
#SBATCH --job-name=test
#SBATCH --gres=gpu:1


source /u/area/ddoimo/anaconda3/bin/activate ./env_amd
export OMP_NUM_THREADS=32
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"

model_name=llama-3-8b
path=llama_v3

torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:0 \
       	--nnodes=1  --nproc-per-node=1 \
    extract_repr.py \
    --dataset_name "mmlu" \
    --model_name_or_path  "/u/area/ddoimo/ddoimo/models/$path/models_hf/$model_name" \
    --preprocessing_num_workers 16 \
    --micro_batch_size 1 \
    --out_dir "./results" \
    --remove_duplicates \
    --max_seq_len 2048 \
    --split "test" \
    --num_few_shots 1 \
    --save_repr \
