#!/bin/bash
#SBATCH --partition=EPYC
##SBATCH --nodelist=dgx001
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=4:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=80G                
#SBATCH --job-name=test

source /u/area/ddoimo/anaconda3/bin/activate ./env_amd

export OMP_NUM_THREADS=32


num_shots=5
python analysis/repr_analysis.py \
    --model_name "llama-3-8b" \
    --results_path "./results/statistics" \
    --layer_path "results/layers/mmlu/pretrained/test/llama-3-8b/$num_shots" \
    --mask_path "analysis/test_mask_200.npy" \
    --eval_dataset "test" \
    --num_shots $num_shots  
