#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
##SBATCH --nodelist=dgx002
#SBATCH --nodes=1
#SBATCH --time=8:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32          
#SBATCH --mem=100G  #it is intended per node          
#SBATCH --job-name=test
#SBATCH --gres=gpu:1 #it is intended per node

poetry shell

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 

TOTAL_BATCH_SIZE=16
BATCH_SIZE_PER_GPU=1

dataset_name="mmlu_pro_race"
dataset_path="/orfeo/cephfs/scratch/area/ddoimo/open/geometric_lens/repo/diego/mmlu_pro_race"
samples_per_subject=50

model_name="llama-3-8b"
folder="llama_v3"


nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

# for some reason the $SLURM_GPUS is empty. We use another way to count the gpus per node used below. 
srun torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w) \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:0 \
   finetune.py \
    --dataset_name $dataset_name \
    --dataset_path $dataset_path \
    --mask_path $dataset_path \
    --samples_per_subject $samples_per_subject \
    --model_name_or_path  /orfeo/cephfs/scratch/area/ddoimo/models/$folder/models_hf/$model_name \
    --tokenizer_name /orfeo/cephfs/scratch/area/ddoimo/models/$folder/models_hf/$model_name \
    --use_lora \
    --lora_rank 64 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --use_slow_tokenizer \
    --low_cpu_mem_usage \
    --max_seq_length 1024 \
    --batch_size $TOTAL_BATCH_SIZE \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.0  \
    --num_train_epochs 1 \
    --output_dir "./results/${model_name}/" \
    --out_filename ""  \
    --checkpointing_steps 10 \
    --logging_steps 20 \
    --eval_steps 4 \
    --weight_samples \
    --use_flash_attn \
    --measure_baselines
    #--activation_checkpointing \
    #--weight_samples \


